
version: '3'
services:
  pulstrat-frontend:
    container_name: pulstrat-frontend
    build: 
      context: ./frontend
      args:
        URL: ${REACT_APP_BASE_URL}
    ports:
      - "3000:3000"

  pulstrate-backend:
    container_name: pulstrate-backend
    build: 
      context: ./backend
      args:
        URI: ${MONGO_URI}
        SECRET: ${SECREY_KEY}
        SENDGRID: ${SENDGRID_API_KEY}
    ports:
      - "5000:5000"

    