name: Pulstrat DockerHub Deployment
on:
  push:
    branches:
      - 'master'

jobs:
    Backend-Deployment:
      runs-on: ubuntu-latest

      steps:
        -
          name: Checkout 
          uses: actions/checkout@v2
        -
          name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        -
          name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: ./backend
            file: ./backend/Dockerfile
            push: true
            build-args: |
              URI=${{ secrets.MONGO_URI }}
              SECRET=${{ secrets.SECRET_KEY }}
              SENDGRID=${{ secrets.SENDGRID_API_KEY }}
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pulstrat:backend




 
    Frontend-Deployment:
      runs-on: ubuntu-latest

      steps:
        -
          name: Checkout 
          uses: actions/checkout@v2
        -
          name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        -
          name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: ./frontend
            file: ./frontend/Dockerfile
            push: true
            build-args: |
              URL=${{ secrets.BASE_URL }}
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pulstrat:frontend